### PR TITLE
Added Marlin Gcode M306 (MPC Autotune)

### PR DESCRIPTION
**Pull request by Prithul0218**
Added the new beta feature in Marlin, MPC autotune. It's an alternative to PID autotune and works better in my experience.
**Source:** https://github.com/MarlinFirmware/Marlin/pull/23751

**The result:**
image

### CODE REVIEW

**Comment by costas-basdekis** [comment]
Hi @Prithul0218 thank you for the contribution!

How did you generate the documentation for these commands? I [auto-generate these every month](https://github.com/costas-basdekis/gcode-documentation-parser/blob/output/output/all_codes.json), and they don't seem to be picked up.

Did you do them by hand? If so, these changes will be lost next time I auto-generate them. I see you linked an MR, perhaps you can ask Marlin to update their documentation?

**Comment by Prithul0218** [comment]
Hi @costas-basdekis 

I did them manually, didn't know there was an auto-generator. Cool stuff!

It seems like there is already a PR in Marlins GCode Documentation repository. It probably just hasn't been merged since it's still a bugfix-only feature. Probably going to be merged when Marlin 2.1 comes out of beta. Maybe you could merge it for now until that comes out? It's also fine if we leave it for now, it'll hopefully be auto-generated when Marlin 2.1 is released along with the documentation. I'll let you decide.

Thank you!

**Comment by costas-basdekis** [comment]
@Prithul0218 I've now included it as a static source in the [parser repo](https://github.com/costas-basdekis/gcode-documentation-parser/blob/main/gcode_documentation_parser/parser/parsers/static_documentation.json).

Thanks for your contribution!

**Comment by costas-basdekis** [comment]
~I've also updated the plugin to get the documentation every month from that repo, so if you update the plugin, you should be able to see it pretty much immediately~

The version hasn't got out yet

**Comment by Prithul0218** [comment]
> @Prithul0218 I've now included it as a static source in the [parser repo](https://github.com/costas-basdekis/gcode-documentation-parser/blob/main/gcode_documentation_parser/parser/parsers/static_documentation.json).
> 
> Thanks for your contribution!

Thank you so much!

**Comment by costas-basdekis** [comment]
Now the plugin is updated.

Update it, and you should be able to see that change

**Pull request closed without merging**
